export const FETCH_DATA = 'CITY_FILTER_PANEL.FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'CITY_FILTER_PANEL.FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'CITY_FILTER_PANEL.FETCH_DATA_FAILED';

// export const FETCH_DATA_MORE = 'CITY_FILTER_PANEL.FETCH_DATA_MORE';
// export const FETCH_DATA_MORE_SUCCESS = 'CITY_FILTER_PANEL.FETCH_DATA_MORE_SUCCESS';
// export const FETCH_DATA_MORE_FAILED = 'CITY_FILTER_PANEL.FETCH_DATA_MORE_FAILED';
