export const FETCH_DATA = 'EVENT_LIST_PANEL.FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'EVENT_LIST_PANEL.FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'EVENT_LIST_PANEL.FETCH_DATA_FAILED';

export const FETCH_DATA_MORE = 'EVENT_LIST_PANEL.FETCH_DATA_MORE';
export const FETCH_DATA_MORE_SUCCESS = 'EVENT_LIST_PANEL.FETCH_DATA_MORE_SUCCESS';
export const FETCH_DATA_MORE_FAILED = 'EVENT_LIST_PANEL.FETCH_DATA_MORE_FAILED';

export const SET_IS_CAN_FETCH_DATA = 'EVENT_LIST_PANEL.SET_IS_CAN_FETCH_DATA';

export const FETCH_DATA_TOP = 'EVENT_LIST_PANEL.FETCH_DATA_TOP';
export const FETCH_DATA_TOP_SUCCESS = 'EVENT_LIST_PANEL.FETCH_DATA_TOP_SUCCESS';
export const FETCH_DATA_TOP_FAILED = 'EVENT_LIST_PANEL.FETCH_DATA_TOP_FAILED';

export const SET_IS_CAN_FETCH_DATA_TOP = 'EVENT_LIST_PANEL.SET_IS_CAN_FETCH_DATA_TOP';


export const SET_IS_HAS_ERROR_MORE = 'EVENT_LIST_PANEL.SET_IS_HAS_ERROR_MORE';
