export const FETCH_DATA = 'OVERVIEW_PLACE_PANEL.FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'OVERVIEW_PLACE_PANEL.FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'OVERVIEW_PLACE_PANEL.FETCH_DATA_FAILED';

export const FETCH_DATA_MORE = 'OVERVIEW_PLACE_PANEL.FETCH_DATA_MORE';
export const FETCH_DATA_MORE_SUCCESS = 'OVERVIEW_PLACE_PANEL.FETCH_DATA_MORE_SUCCESS';
export const FETCH_DATA_MORE_FAILED = 'OVERVIEW_PLACE_PANEL.FETCH_DATA_MORE_FAILED';

export const SET_IS_CAN_FETCH_DATA = 'OVERVIEW_PLACE_PANEL.SET_IS_CAN_FETCH_DATA';
