export const FETCH_DATA = 'SHOWINGS_PANEL.FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'SHOWINGS_PANEL.FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'SHOWINGS_PANEL.FETCH_DATA_FAILED';

export const CLEAR_DATA = 'SHOWINGS_PANEL.CLEAR_DATA';

export const SET_MOVIE_ID = 'SHOWINGS_PANEL.SET_MOVIE_ID';

export const SET_BACK_PANEL = 'SHOWINGS_PANEL.SET_BACK_PANEL';
