export const FETCH_PLACE = 'EVENT_LIST_PANEL.FETCH_PLACE';
export const FETCH_PLACE_SUCCESS = 'EVENT_LIST_PANEL.FETCH_PLACE_SUCCESS';
export const FETCH_PLACE_FAILED = 'EVENT_LIST_PANEL.FETCH_PLACE_FAILED';

export const FETCH_PLACE_MORE = 'EVENT_LIST_PANEL.FETCH_PLACE_MORE';
export const FETCH_PLACE_MORE_SUCCESS = 'EVENT_LIST_PANEL.FETCH_PLACE_MORE_SUCCESS';
export const FETCH_PLACE_MORE_FAILED = 'EVENT_LIST_PANEL.FETCH_PLACE_MORE_FAILED';

export const SET_IS_CAN_FETCH_PLACE = 'EVENT_LIST_PANEL.SET_IS_CAN_FETCH_PLACE';




export const FETCH_EVENT = 'EVENT_LIST_PANEL.FETCH_EVENT';
export const FETCH_EVENT_SUCCESS = 'EVENT_LIST_PANEL.FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAILED = 'EVENT_LIST_PANEL.FETCH_EVENT_FAILED';

export const FETCH_EVENT_MORE = 'EVENT_LIST_PANEL.FETCH_EVENT_MORE';
export const FETCH_EVENT_MORE_SUCCESS = 'EVENT_LIST_PANEL.FETCH_EVENT_MORE_SUCCESS';
export const FETCH_EVENT_MORE_FAILED = 'EVENT_LIST_PANEL.FETCH_EVENT_MORE_FAILED';

export const SET_IS_CAN_FETCH_EVENT = 'EVENT_LIST_PANEL.SET_IS_CAN_FETCH_EVENT';

