export const FETCH_DATA = 'FAVORITES_PANEL.FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FAVORITES_PANEL.FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'FAVORITES_PANEL.FETCH_DATA_FAILED';

export const FETCH_DATA_MORE = 'FAVORITES_PANEL.FETCH_DATA_MORE';
export const FETCH_DATA_MORE_SUCCESS = 'FAVORITES_PANEL.FETCH_DATA_MORE_SUCCESS';
export const FETCH_DATA_MORE_FAILED = 'FAVORITES_PANEL.FETCH_DATA_MORE_FAILED';

export const SET_IS_CAN_FETCH_DATA = 'FAVORITES_PANEL.SET_IS_CAN_FETCH_DATA';


export const SET_IS_HAS_ERROR_MORE = 'FAVORITES_PANEL.SET_IS_HAS_ERROR_MORE';

