export const FETCH_DATA = 'SEARCH_PANEL.FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'SEARCH_PANEL.FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'SEARCH_PANEL.FETCH_DATA_FAILED';

export const FETCH_DATA_MORE = 'SEARCH_PANEL.FETCH_DATA_MORE';
export const FETCH_DATA_MORE_SUCCESS = 'SEARCH_PANEL.FETCH_DATA_MORE_SUCCESS2';
export const FETCH_DATA_MORE_FAILED = 'SEARCH_PANEL.FETCH_DATA_MORE_FAILED2';

export const SET_SEARCH = 'SEARCH_PANEL.SET_SEARCH';

export const TOGGLE_CONTEXT = 'SEARCH_PANEL.TOGGLE_CONTEXT';
export const SET_MODE = 'SEARCH_PANEL.SET_MODE';
export const SET_IS_NOT_FOUND = 'SEARCH_PANEL.SET_IS_NOT_FOUND';

