// export const FETCH_DATA = 'EVENT_PANEL.FETCH_DATA';
// export const FETCH_DATA_SUCCESS = 'EVENT_PANEL.FETCH_DATA_SUCCESS';
// export const FETCH_DATA_FAILED = 'EVENT_PANEL.FETCH_DATA_FAILED';

// export const SET_EVENT_ID = 'APP_CONTAINER.SET_EVENT_ID';
export const SET_CITY_ID = 'APP_CONTAINER.SET_CITY_ID';
export const SET_EVENT_TYPE_ID = 'APP_CONTAINER.SET_EVENT_TYPE_ID';
export const SET_PLACE_TYPE_ID = 'APP_CONTAINER.SET_PLACE_TYPE_ID';
export const SET_CATEGORIES_TYPE_ID = 'APP_CONTAINER.SET_CATEGORIES_TYPE_ID';
export const SET_IS_FREE_TYPE = 'APP_CONTAINER.SET_IS_FREE_TYPE';
export const SET_DATE_TYPE_ID = 'APP_CONTAINER.SET_DATE_TYPE_ID';
export const SET_SEARCH_RADIUS = 'APP_CONTAINER.SET_SEARCH_RADIUS';
export const SET_IS_SHOW_POPOUT = 'APP_CONTAINER.SET_IS_SHOW_POPOUT';


export const INIT_APP = 'APP_CONTAINER.INIT_APP';
