export const FETCH_DATA = 'EVENT_PANEL.FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'EVENT_PANEL.FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'EVENT_PANEL.FETCH_DATA_FAILED';

export const CLEAR_DATA = 'EVENT_PANEL.CLEAR_DATA';

export const SET_EVENT_ID = 'EVENT_PANEL.SET_EVENT_ID';

export const SET_BACK_PANEL = 'EVENT_PANEL.SET_BACK_PANEL';
