export const FETCH_DATA = 'MAP_PANEL.FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'MAP_PANEL.FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'MAP_PANEL.FETCH_DATA_FAILED';

export const SET_PLACES = 'MAP_PANEL.SET_PLACES';
export const SET_BACK_PANEL = 'MAP_PANEL.SET_BACK_PANEL';
