// export const FETCH_DATA = 'FILTER_PANEL.FETCH_DATA';
// export const FETCH_DATA_SUCCESS = 'FILTER_PANEL.FETCH_DATA_SUCCESS';
// export const FETCH_DATA_FAILED = 'FILTER_PANEL.FETCH_DATA_FAILED';

// export const FETCH_DATA_MORE = 'FILTER_PANEL.FETCH_DATA_MORE';
// export const FETCH_DATA_MORE_SUCCESS = 'FILTER_PANEL.FETCH_DATA_MORE_SUCCESS';
// export const FETCH_DATA_MORE_FAILED = 'FILTER_PANEL.FETCH_DATA_MORE_FAILED';


export const SET_EVENT_TYPE_ID = 'FILTER_PANEL.SET_EVENT_TYPE_ID';
export const SET_PLACE_TYPE_ID = 'FILTER_PANEL.SET_PLACE_TYPE_ID';
export const SET_CATEGORIES_TYPE_ID = 'FILTER_PANEL.SET_CATEGORIES_TYPE_ID';
export const SET_IS_FREE_TYPE = 'FILTER_PANEL.SET_IS_FREE_TYPE';
export const SET_DATE_TYPE_ID = 'FILTER_PANEL.SET_DATE_TYPE_ID';
export const SET_SEARCH_RADIUS = 'FILTER_PANEL.SET_SEARCH_RADIUS';
